/////////////////////////////////////////////////////////////////////////////
//
// include/effects.inc - special effects declarations
//
/////////////////////////////////////////////////////////////////////////////

Const MOVING_EFFECT_FIREBALL		:= 0x36D4;
Const MOVING_EFFECT_FROST		:= 0x373a;

Const MOVING_EFFECT_ARROW		:= 0x0f42;
Const MOVING_EFFECT_BOLT			:= 0x1bfe;

Const EFFECT_FIZZLE		:= 0x3735;
Const EFFECT_RESIST		:= 0x374a;


