
// wazne x, y, z

const FRAKCJA_1_X := 2509; // miasto blue (minoc)
const FRAKCJA_1_Y := 560;
const FRAKCJA_1_Z := 0;


const FRAKCJA_2_X := 2509; // miasto blue (minoc)
const FRAKCJA_2_Y := 560;
const FRAKCJA_2_Z := 0;


const BARN_X := 5295; // horsebarn
const BARN_Y := 1173;
const BARN_Z := 0;


// NAROZNIKI ARENY DUELOWEJ

const LEFT_CORNER_X := 1412;
const LEFT_CORNER_Y := 3729;
const LEFT_CORNER_Z := -21;

const RIGHT_CORNER_X := 1385;
const RIGHT_CORNER_Y := 3758;
const RIGHT_CORNER_Z := -20;
